In [ ]:
!pip install transformers

Collecting transformers
  Downloading transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (6.0.2)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.6.28-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (0.9.0)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (4.67.1)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\kisha\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: anyio in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\kisha\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kisha\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Downloading transformers-5.13.0-py3-none-any.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 5.2 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.5 MB 5.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.5 MB 5.7 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.5 MB 6.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.5 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.5 MB 5.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 5.9 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 6.0 MB/s eta 0:00:00
Downloading huggingface_hub-1.22.0-py3-none-any.whl (765 kB)
   ---------------------------------------- 0.0/765.1 kB ? eta -:--:--
   ---------------------------------------- 765.1/765.1 kB 7.0 MB/s eta 0:00:00
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------- -------------------------- 1.3/4.0 MB 7.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 7.0 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.5 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --------------- ------------------------ 1.0/2.7 MB 5.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 4.6 MB/s eta 0:00:00
Downloading regex-2026.6.28-cp313-cp313-win_amd64.whl (277 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Installing collected packages: safetensors, regex, hf-xet, click, huggingface-hub, tokenizers, transformers

  Attempting uninstall: regex

    Found existing installation: regex 2024.11.6

    Uninstalling regex-2024.11.6:

      Successfully uninstalled regex-2024.11.6

   ----- ---------------------------------- 1/7 [regex]
   ----------- ---------------------------- 2/7 [hf-xet]
  Attempting uninstall: click
   ----------- ---------------------------- 2/7 [hf-xet]
    Found existing installation: click 8.1.8
   ----------- ---------------------------- 2/7 [hf-xet]
    Uninstalling click-8.1.8:
   ----------- ---------------------------- 2/7 [hf-xet]
      Successfully uninstalled click-8.1.8
   ----------- ---------------------------- 2/7 [hf-xet]
   ----------------- ---------------------- 3/7 [click]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------------- ----------- 5/7 [tokenizers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------------- 7/7 [transformers]

Successfully installed click-8.4.2 hf-xet-1.5.1 huggingface-hub-1.22.0 regex-2026.6.28 safetensors-0.8.0 tokenizers-0.22.2 transformers-5.13.0

In [2]:
!pip install "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\users\kisha\anaconda3\lib\site-packages (5.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (1.22.0)
Requirement already satisfied: numpy>=1.17 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2.11.0)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: colorama in c:\users\kisha\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: anyio in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.7.0)
Requirement already satisfied: certifi in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\kisha\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: psutil in c:\users\kisha\anaconda3\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (5.9.0)
Requirement already satisfied: setuptools<82 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kisha\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kisha\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0

In [1]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [2]:
train_data = pd.read_csv("samsumdataset/samsum-train.csv")
val_data = pd.read_csv("samsumdataset/samsum-validation.csv")

In [3]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [4]:
train_data['dialogue'][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [5]:
train_data.sample(10)

,id,dialogue,summary
7777,13730890,Fran: I can't find my boarding pass. Have you ...,Jim helps Fran find her boarding pass in the d...
13792,13730005,"Randy: Hi, I'm writing about the stroller you ...",Randy is interested in the stroller Todd is se...
3635,13810144,"Hailey: heyoooo, I got an important question f...",Hailey invites Peter for a house-warming part ...
10335,13681683,Melissa: Is there any more info on Grandma?\r\...,Grandma is recovering after a health incident....
44,13682379,Linda: I'm going to have my room painted\r\nLi...,"According to Brian, colors that match Linda's ..."
7042,13818836,Marie: would any of you be a dear and put the ...,Vanessa can put the pot with soup on the stove...
14576,13728361-1,"Ian: U on campus? Lunch at AW?\r\nViola: Yes, ...",Viola invited Ian for lunch with her parents. ...
7250,13680801,Nora: how r u? How r u feeling?\r\nJane: same ...,"Jane was at the doctor, she is 7 months pregna..."
8124,13829671,Kim: did you bring back the car?\r\nJane: yes\...,Jane brought back the car.
3741,13817611,"Kai: did you know, that there are several medi...",Rapunzel syndrome is one of the medical condit...

In [6]:
print("train", train_data.shape)
print("validation", val_data.shape)

train (14732, 3)
validation (818, 3)

In [7]:
# random sampling

train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

In [8]:
train_data.shape

(4000, 3)

In [9]:
val_data.shape

(500, 3)

### data pre-processing

In [10]:
import re